services:
  db:
    image: postgres:15
    container_name: pokemon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pokedex_user
      POSTGRES_PASSWORD: pokedex_pass
      POSTGRES_DB: pokemon_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis-data:/data # Persist data across container restarts

volumes:
  pgdata:
  redis-data:
