version: '3.9'

services:
  db:
    image: postgres:15
    container_name: pokemon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pokedex_user
      POSTGRES_PASSWORD: pokedex_pass
      POSTGRES_DB: pokemon_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
